// Package docs embeds the OpenAPI document generated by `make docs`.
//
// swagger.json and swagger.yaml are generated from the swag annotations and are
// not edited by hand. Embedding them keeps the document a build artefact rather
// than something assembled at runtime.
package docs

import _ "embed"

// OpenAPI is the generated OpenAPI 3.1 document.
//
//go:embed swagger.json
var OpenAPI []byte
